#!/usr/bin/env bash
# Install nginx web server
# Replace default page with Holberton School
apt update
apt-get -y install nginx
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
if ["$(pgrep -c nginx)" ls 0]; then
    service nginx start
else
    service nginx restart
fi
