#!/usr/bin/env bash
# Install nginx web server
# Replace default page with Holberton School
apt update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.html
service nginx start
